name: GitHub Actions Build and Deploy
on: 
  push:
    branches: [ master ]
    paths: "site/**"
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - name: Change package.json
        run: |
          rm package.json package-lock.json
          mv package-ci.json package.json
          mv package-lock-ci.json package-lock.json
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci --ignore-scripts
      - run: npm run build
      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site
      - name: Deploy pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}